/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javasolutions;

import java.util.ArrayList;

public class App {
    public void run() throws Exception {
        var days = new ArrayList<ADay>();
        days.add(new Day11());
        for (var day : days) {
            var a = day.partA();
            var b = day.partB();
            System.out.println(String.format("A: %s B: %s", a, b));
        }
    }

    public static void main(String[] args) {
        new App().run();
    }
}
